// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sshist_cost_cpp
NumericVector sshist_cost_cpp(NumericVector x, IntegerVector N_vector, int sn, double x_min, double x_max);
RcppExport SEXP _sshist_sshist_cost_cpp(SEXP xSEXP, SEXP N_vectorSEXP, SEXP snSEXP, SEXP x_minSEXP, SEXP x_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N_vector(N_vectorSEXP);
    Rcpp::traits::input_parameter< int >::type sn(snSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(sshist_cost_cpp(x, N_vector, sn, x_min, x_max));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sshist_sshist_cost_cpp", (DL_FUNC) &_sshist_sshist_cost_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_sshist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
