# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sshist_cost_cpp <- function(x, N_vector, sn, x_min, x_max) {
    .Call(`_sshist_sshist_cost_cpp`, x, N_vector, sn, x_min, x_max)
}

