# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sshist_cost_cpp <- function(x, N_vector, sn, x_min, x_max, n_threads) {
    .Call(`_sshist_sshist_cost_cpp`, x, N_vector, sn, x_min, x_max, n_threads)
}

get_tau_bounds_cpp <- function(xn, yn, n_threads) {
    .Call(`_sshist_get_tau_bounds_cpp`, xn, yn, n_threads)
}

compute_sskernel2d_cost_cpp <- function(xn, yn, w, n_threads) {
    .Call(`_sshist_compute_sskernel2d_cost_cpp`, xn, yn, w, n_threads)
}

compute_pilot_density_cpp <- function(x, y, wx, wy, n_threads) {
    .Call(`_sshist_compute_pilot_density_cpp`, x, y, wx, wy, n_threads)
}

compute_kde2d_cpp <- function(x, y, gx, gy, wx, wy, n_threads) {
    .Call(`_sshist_compute_kde2d_cpp`, x, y, gx, gy, wx, wy, n_threads)
}

